root = "."
testdata_dir = "testdata"
tmp_dir = "temp"

[build]
args_bin = ["--config ./custom.config.toml"]
bin = "temp\\main.exe"
cmd = "go build -o ./temp/main.exe ."
delay = 1000
exclude_dir = ["assets", "temp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
