# 服务器配置
[Server]
Debug = false                           # 调试模式
Port = 8080                             # 发布服务端口                      
Templates = "./../app/templates/*.html" # 模板目录

# 静态 Web 文件服务目录配置
[Server.Static]
# 外观文件目录, 存放思源笔记工作区 /conf/appearance/ 目录下的文件
Appearance.Path = "/appearance"                    # 访问目录
Appearance.FilePath = "./../app/static/appearance" # 文件目录

# 资源文件目录, 存放思源笔记工作区 /data/assets/ 目录下的文件
Assets.Path = "/assets"                    # 访问目录
Assets.FilePath = "./../app/static/assets" # 文件目录

# 表情文件目录, 存放思源笔记工作区 /data/emojis/ 目录下的文件
Emojis.Path = "/emojis"                    # 访问目录
Emojis.FilePath = "./../app/static/emojis" # 文件目录

# 挂件文件目录, 存放思源笔记工作区 /data/widgets/ 目录下的文件
Widgets.Path = "/widgets"                    # 访问目录
Widgets.FilePath = "./../app/static/widgets" # 文件目录

# 思源应用文件目录, 存放思源笔记安装目录中 /resources/stage/ 目录下的文件
Stage.Path = "/stage"                    # 访问目录
Stage.FilePath = "./../app/static/stage" # 文件目录

# 前端 JavaScript 文件目录, 存放异步加载的 JavaScript 文件
JavaScript.Path = "/js"                 # 访问目录
JavaScript.FilePath = "./../app/src/js" # 文件目录

# 前端 CSS 文件目录, 存放异步加载的 CSS 文件
CSS.Path = "/css"                 # 访问目录
CSS.FilePath = "./../app/src/css" # 文件目录


# 思源适配器配置
[Siyuan]
Server = "http://localhost:6806" # 思源内核服务地址
Token = ""                       # 思源内核服务访问令牌
Timeout = 10_000                 # 向思源内核发起 HTTP 请求的超时时间(单位: ms)
Retry = 3                        # 向思源内核发起 HTTP 请求的重试次数

# 思源发布相关设置
[Siyuan.Publish]

# 思源发布内容访问权限控制属性
[Siyuan.Publish.Access]
# 请保持下列字段的 Name 值一致
Name = "custom-publish-access" # 属性名称
Public.Value = "public"        # 可公开访问的文档的属性值(白名单)
Protected.Value = "protected"  # 鉴权后可公开访问的文档的属性值
Private.Value = "private"      # 不可公开访问的文档的属性值(黑名单)

# 渲染器配置
[Render]

# 外观设置
[Render.Appearance]
Mode = 0                               # 主题模式, 0: 明亮模式, 1: 暗黑模式, 2: 自动模式
CodeBlockThemeLight = "atom-one-light" # 明亮模式代码块配色方案
CodeBlockThemeDark = "atom-one-dark"   # 暗黑模式代码块配色方案

# 编辑器设置
[Render.Editor]
FontSize = 16                                                  # 编辑器字体大小(单位: px)
CodeLineWrap = true                                            # 代码行是否启用自动换行
CodeLigatures = true                                           # 代码是否启用连字符
CodeSyntaxHighlightLineNum = true                              # 代码块是否显示行号
PlantUMLServePath = "https://www.plantuml.com/plantuml/svg/~1" # plant UML 渲染服务 URL

# 渲染器资源文件目录
[Render.Path]
Protyle = "/stage/protyle" # 渲染器 protyle 资源目录

# 渲染器资源文件 URL
[Render.File]

# 渲染器样式文件 URL
[Render.File.Style]
Base = "/stage/build/export/base.css" # 基础样式文件 URL
Publish = "/css/publish.css"          # 发布样式文件 URL

# 渲染器明亮主题样式文件 URL
[Render.File.Style.Light]
Default = "/appearance/themes/daylight/theme.css" # 基础主题配色
Theme = "/appearance/themes/daylight/theme.css"   # 主题样式
Custom = "/appearance/themes/daylight/custom.css" # 自定义主题样式

# 渲染器暗黑主题样式文件 URL
[Render.File.Style.Dark]
Default = "/appearance/themes/midnight/theme.css" # 基础主题配色
Theme = "/appearance/themes/midnight/theme.css"   # 主题样式
Custom = "/appearance/themes/midnight/custom.css" # 自定义主题样式

# 渲染器脚本文件 URL
[Render.File.Script]
Icon = "/appearance/icons/material/icon.js"       # 图标脚本 URL
Emoji = "/appearance/emojis/twitter-emoji.js"     # 表情脚本 URL
Lute = "/stage/protyle/js/lute/lute.min.js"       # 解析器脚本 URL
HTML = "/stage/protyle/js/protyle-html.js"        # HTML 解析脚本 URL
Protyle = "/stage/build/export/protyle-method.js" # 渲染器脚本 URL
Config = "/js/config.js"                          # 配置脚本 URL
Publish = "/js/publish.js"                        # 发布脚本 URL
