name: goreleaser
# REF [触发工作流程 - GitHub Docs](https://docs.github.com/cn/actions/using-workflows/triggering-a-workflow)
on:
  # REF [触发工作流程的事件 - GitHub Docs](https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows)
  # REF [push](https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#push)
  push:
    tags:
      - v*

# REF [GoReleaser Action · Actions · GitHub Marketplace · GitHub](https://github.com/marketplace/actions/goreleaser-action)
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          workdir: '.'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
